# Generated by Django 4.2 on 2024-06-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=5, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=2)),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('ICT', 'B.Tech ICT'), ('ICT-CS', 'B.Tech ICT-CS'), ('MnC', 'B.Tech MnC'), ('M.Tech', 'M.Tech')], max_length=15)),
                ('batch', models.CharField(choices=[('2021', 'Final Year'), ('2022', 'Third Year'), ('2023', 'Second Year'), ('2024', 'First Year')], max_length=15)),
                ('category', models.CharField(choices=[('ICTE', 'ICT Elective'), ('TE', 'Technical Elective'), ('SE', 'Science Elective'), ('CS-ICTE', 'CS ICT Elective'), ('CS-TE', 'CS Technical Elective'), ('CS-SE', 'CS Science Elective'), ('MnCE', 'MnC Elective'), ('HASSE', 'HASSE Elective'), ('OE', 'Open Elective')], max_length=15)),
                ('seats', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(choices=[('ICT', 'B.Tech ICT'), ('ICT-CS', 'B.Tech ICT-CS'), ('MnC', 'B.Tech MnC'), ('M.Tech', 'M.Tech')], max_length=15)),
                ('batch', models.CharField(choices=[('2021', 'Final Year'), ('2022', 'Third Year'), ('2023', 'Second Year'), ('2024', 'First Year')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('preference_index', models.IntegerField()),
                ('course_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.openfor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.openfor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentuser')),
            ],
        ),
    ]
