# Generated by Django 4.2 on 2024-06-06 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(unique=True)),
                ('program', models.CharField(choices=[('ICT', 'B.Tech ICT'), ('ICT-CS', 'B.Tech ICT-CS'), ('MnC', 'B.Tech MnC'), ('M.Tech', 'M.Tech')], max_length=15)),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
    ]
