# Generated by Django 4.2 on 2024-06-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='batch',
            field=models.CharField(choices=[('2021', 'Final Year'), ('2022', 'Third Year'), ('2023', 'Second Year'), ('2024', 'First Year')], max_length=15),
        ),
    ]
