# Generated by Django 4.2 on 2024-10-30 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_allocationresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllocationResult',
        ),
    ]
